// <auto-generated />
using System;
using HiWebAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HiWebAPI.Migrations
{
    [DbContext(typeof(context))]
    partial class contextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HiWebAPI.Models.Gift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("giftNet")
                        .HasColumnType("int");

                    b.Property<DateTime>("lastGiftTimeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("lastGiftTimeString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("remainNet")
                        .HasColumnType("int");

                    b.Property<int>("totalNet")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("gifts");
                });
#pragma warning restore 612, 618
        }
    }
}
